# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='log.protocol/ClientLog.proto',
  package='protocal.log',
  serialized_pb='\n\x1clog.protocol/ClientLog.proto\x12\x0cprotocal.log\"\x8b\x01\n\rReqSubmitInfo\x12\x34\n\x04type\x18\x02 \x02(\x0e\x32&.protocal.log.ReqSubmitInfo.SubmitType\x12\x13\n\x0b\x65rr_content\x18\x03 \x02(\t\"/\n\nSubmitType\x12\x08\n\x04INFO\x10\x00\x12\x07\n\x03\x45RR\x10\x01\x12\x0e\n\nSTATISTICS\x10\x02\"\x1d\n\x08ReqHeart\x12\x11\n\theart_num\x18\x01 \x02(\x05*\x1c\n\x07ProtoID\x12\x11\n\rREQSUBMITINFO\x10\x01')

_PROTOID = descriptor.EnumDescriptor(
  name='ProtoID',
  full_name='protocal.log.ProtoID',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='REQSUBMITINFO', index=0, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=219,
  serialized_end=247,
)


REQSUBMITINFO = 1


_REQSUBMITINFO_SUBMITTYPE = descriptor.EnumDescriptor(
  name='SubmitType',
  full_name='protocal.log.ReqSubmitInfo.SubmitType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='INFO', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ERR', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STATISTICS', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=139,
  serialized_end=186,
)


_REQSUBMITINFO = descriptor.Descriptor(
  name='ReqSubmitInfo',
  full_name='protocal.log.ReqSubmitInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='protocal.log.ReqSubmitInfo.type', index=0,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='err_content', full_name='protocal.log.ReqSubmitInfo.err_content', index=1,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQSUBMITINFO_SUBMITTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=47,
  serialized_end=186,
)


_REQHEART = descriptor.Descriptor(
  name='ReqHeart',
  full_name='protocal.log.ReqHeart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='heart_num', full_name='protocal.log.ReqHeart.heart_num', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=188,
  serialized_end=217,
)

_REQSUBMITINFO.fields_by_name['type'].enum_type = _REQSUBMITINFO_SUBMITTYPE
_REQSUBMITINFO_SUBMITTYPE.containing_type = _REQSUBMITINFO;
DESCRIPTOR.message_types_by_name['ReqSubmitInfo'] = _REQSUBMITINFO
DESCRIPTOR.message_types_by_name['ReqHeart'] = _REQHEART

class ReqSubmitInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQSUBMITINFO
  
  # @@protoc_insertion_point(class_scope:protocal.log.ReqSubmitInfo)

class ReqHeart(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQHEART
  
  # @@protoc_insertion_point(class_scope:protocal.log.ReqHeart)

# @@protoc_insertion_point(module_scope)
