# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='log.protocol/SystemIndex.proto',
  package='protocal.log',
  serialized_pb='\n\x1elog.protocol/SystemIndex.proto\x12\x0cprotocal.log*\x1b\n\nSystemType\x12\r\n\tCLIENTLOG\x10\x01')

_SYSTEMTYPE = descriptor.EnumDescriptor(
  name='SystemType',
  full_name='protocal.log.SystemType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='CLIENTLOG', index=0, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=48,
  serialized_end=75,
)


CLIENTLOG = 1



# @@protoc_insertion_point(module_scope)
