# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='gameserver.protocol/Formation.proto',
  package='protocal.game.FormationProto',
  serialized_pb='\n#gameserver.protocol/Formation.proto\x12\x1cprotocal.game.FormationProto\",\n\x14\x46ormationInfoRequest\x12\x14\n\x0c\x66ormationNum\x18\x01 \x02(\x05\"_\n\x15\x46ormationInfoResponse\x12\x46\n\x11\x62\x61ttleEmployeList\x18\x01 \x03(\x0b\x32+.protocal.game.FormationProto.BattleEmploye\"2\n\rBattleEmploye\x12\x12\n\nemployeUid\x18\x01 \x02(\x03\x12\r\n\x05index\x18\x02 \x02(\x05\"^\n\x14\x46ormationSaveRequest\x12\x46\n\x11\x62\x61ttleEmployeList\x18\x01 \x03(\x0b\x32+.protocal.game.FormationProto.BattleEmploye\"\x17\n\x15\x46ormationSaveResponse\"<\n\x16\x46ormationAssistRequest\x12\x12\n\nemployeUid\x18\x01 \x02(\x03\x12\x0e\n\x06\x61ssist\x18\x02 \x03(\x03\"\x19\n\x17\x46ormationAssistResponse*\xb6\x01\n\x07ProtoID\x12\x16\n\x12\x46ORMATION_INFO_REQ\x10\x01\x12\x1b\n\x17\x46ORMATION_INFO_RESPONSE\x10\x02\x12\x16\n\x12\x46ORMATION_SAVE_REQ\x10\x03\x12\x1b\n\x17\x46ORMATION_SAVE_RESPONSE\x10\x04\x12\x1d\n\x19\x46ORMATION_ASSIST_SAVE_REQ\x10\x05\x12\"\n\x1e\x46ORMATION_ASSIST_SAVE_RESPONSE\x10\x06')

_PROTOID = descriptor.EnumDescriptor(
  name='ProtoID',
  full_name='protocal.game.FormationProto.ProtoID',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='FORMATION_INFO_REQ', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FORMATION_INFO_RESPONSE', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FORMATION_SAVE_REQ', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FORMATION_SAVE_RESPONSE', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FORMATION_ASSIST_SAVE_REQ', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FORMATION_ASSIST_SAVE_RESPONSE', index=5, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=475,
  serialized_end=657,
)


FORMATION_INFO_REQ = 1
FORMATION_INFO_RESPONSE = 2
FORMATION_SAVE_REQ = 3
FORMATION_SAVE_RESPONSE = 4
FORMATION_ASSIST_SAVE_REQ = 5
FORMATION_ASSIST_SAVE_RESPONSE = 6



_FORMATIONINFOREQUEST = descriptor.Descriptor(
  name='FormationInfoRequest',
  full_name='protocal.game.FormationProto.FormationInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='formationNum', full_name='protocal.game.FormationProto.FormationInfoRequest.formationNum', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=69,
  serialized_end=113,
)


_FORMATIONINFORESPONSE = descriptor.Descriptor(
  name='FormationInfoResponse',
  full_name='protocal.game.FormationProto.FormationInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='battleEmployeList', full_name='protocal.game.FormationProto.FormationInfoResponse.battleEmployeList', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=115,
  serialized_end=210,
)


_BATTLEEMPLOYE = descriptor.Descriptor(
  name='BattleEmploye',
  full_name='protocal.game.FormationProto.BattleEmploye',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='employeUid', full_name='protocal.game.FormationProto.BattleEmploye.employeUid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='index', full_name='protocal.game.FormationProto.BattleEmploye.index', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=212,
  serialized_end=262,
)


_FORMATIONSAVEREQUEST = descriptor.Descriptor(
  name='FormationSaveRequest',
  full_name='protocal.game.FormationProto.FormationSaveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='battleEmployeList', full_name='protocal.game.FormationProto.FormationSaveRequest.battleEmployeList', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=264,
  serialized_end=358,
)


_FORMATIONSAVERESPONSE = descriptor.Descriptor(
  name='FormationSaveResponse',
  full_name='protocal.game.FormationProto.FormationSaveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=360,
  serialized_end=383,
)


_FORMATIONASSISTREQUEST = descriptor.Descriptor(
  name='FormationAssistRequest',
  full_name='protocal.game.FormationProto.FormationAssistRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='employeUid', full_name='protocal.game.FormationProto.FormationAssistRequest.employeUid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='assist', full_name='protocal.game.FormationProto.FormationAssistRequest.assist', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=385,
  serialized_end=445,
)


_FORMATIONASSISTRESPONSE = descriptor.Descriptor(
  name='FormationAssistResponse',
  full_name='protocal.game.FormationProto.FormationAssistResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=447,
  serialized_end=472,
)

_FORMATIONINFORESPONSE.fields_by_name['battleEmployeList'].message_type = _BATTLEEMPLOYE
_FORMATIONSAVEREQUEST.fields_by_name['battleEmployeList'].message_type = _BATTLEEMPLOYE
DESCRIPTOR.message_types_by_name['FormationInfoRequest'] = _FORMATIONINFOREQUEST
DESCRIPTOR.message_types_by_name['FormationInfoResponse'] = _FORMATIONINFORESPONSE
DESCRIPTOR.message_types_by_name['BattleEmploye'] = _BATTLEEMPLOYE
DESCRIPTOR.message_types_by_name['FormationSaveRequest'] = _FORMATIONSAVEREQUEST
DESCRIPTOR.message_types_by_name['FormationSaveResponse'] = _FORMATIONSAVERESPONSE
DESCRIPTOR.message_types_by_name['FormationAssistRequest'] = _FORMATIONASSISTREQUEST
DESCRIPTOR.message_types_by_name['FormationAssistResponse'] = _FORMATIONASSISTRESPONSE

class FormationInfoRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FORMATIONINFOREQUEST
  
  # @@protoc_insertion_point(class_scope:protocal.game.FormationProto.FormationInfoRequest)

class FormationInfoResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FORMATIONINFORESPONSE
  
  # @@protoc_insertion_point(class_scope:protocal.game.FormationProto.FormationInfoResponse)

class BattleEmploye(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BATTLEEMPLOYE
  
  # @@protoc_insertion_point(class_scope:protocal.game.FormationProto.BattleEmploye)

class FormationSaveRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FORMATIONSAVEREQUEST
  
  # @@protoc_insertion_point(class_scope:protocal.game.FormationProto.FormationSaveRequest)

class FormationSaveResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FORMATIONSAVERESPONSE
  
  # @@protoc_insertion_point(class_scope:protocal.game.FormationProto.FormationSaveResponse)

class FormationAssistRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FORMATIONASSISTREQUEST
  
  # @@protoc_insertion_point(class_scope:protocal.game.FormationProto.FormationAssistRequest)

class FormationAssistResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FORMATIONASSISTRESPONSE
  
  # @@protoc_insertion_point(class_scope:protocal.game.FormationProto.FormationAssistResponse)

# @@protoc_insertion_point(module_scope)
