# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import gameserver.protocol.Role_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='gameserver.protocol/Lottery.proto',
  package='protocal.game.LotteryProto',
  serialized_pb='\n!gameserver.protocol/Lottery.proto\x12\x1aprotocal.game.LotteryProto\x1a\x1egameserver.protocol/Role.proto\"\x14\n\x12LotteryInfoRequest\"T\n\x13LotteryInfoResponse\x12\x11\n\tfreeTimes\x18\x01 \x02(\x05\x12\x11\n\tcountDown\x18\x02 \x02(\x05\x12\x17\n\x0fgetEmployeTimes\x18\x03 \x02(\x05\"\x1e\n\x0eLotteryRequest\x12\x0c\n\x04type\x18\x01 \x02(\x05\"\xba\x01\n\x0fLotteryResponse\x12\x38\n\tawardInfo\x18\x01 \x03(\x0b\x32%.protocal.game.LotteryProto.AwardInfo\x12\x39\n\x0b\x65mployeList\x18\x02 \x03(\x0b\x32$.protocal.game.RoleProto.EmployeInfo\x12\x32\n\x08\x61\x64\x64Items\x18\x03 \x03(\x0b\x32 .protocal.game.RoleProto.BagItem\"\x9b\x01\n\tAwardInfo\x12\r\n\x05index\x18\x01 \x02(\x05\x12\x32\n\x08\x61\x64\x64Items\x18\x02 \x01(\x0b\x32 .protocal.game.RoleProto.BagItem\x12:\n\x08\x65mployes\x18\x03 \x01(\x0b\x32(.protocal.game.LotteryProto.AwardEmploye\x12\x0f\n\x07\x64iamond\x18\x04 \x01(\x05\"4\n\x0c\x41wardEmploye\x12\x11\n\temployeId\x18\x01 \x02(\x05\x12\x11\n\tclothesId\x18\x02 \x02(\x05*a\n\x07ProtoID\x12\x14\n\x10LOTTERY_INFO_REQ\x10\x01\x12\x19\n\x15LOTTERY_INFO_RESPINSE\x10\x02\x12\x0f\n\x0bLOTTERY_REQ\x10\x03\x12\x14\n\x10LOTTERY_RESPINSE\x10\x04')

_PROTOID = descriptor.EnumDescriptor(
  name='ProtoID',
  full_name='protocal.game.LotteryProto.ProtoID',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='LOTTERY_INFO_REQ', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LOTTERY_INFO_RESPINSE', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LOTTERY_REQ', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LOTTERY_RESPINSE', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=638,
  serialized_end=735,
)


LOTTERY_INFO_REQ = 1
LOTTERY_INFO_RESPINSE = 2
LOTTERY_REQ = 3
LOTTERY_RESPINSE = 4



_LOTTERYINFOREQUEST = descriptor.Descriptor(
  name='LotteryInfoRequest',
  full_name='protocal.game.LotteryProto.LotteryInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=97,
  serialized_end=117,
)


_LOTTERYINFORESPONSE = descriptor.Descriptor(
  name='LotteryInfoResponse',
  full_name='protocal.game.LotteryProto.LotteryInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='freeTimes', full_name='protocal.game.LotteryProto.LotteryInfoResponse.freeTimes', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='countDown', full_name='protocal.game.LotteryProto.LotteryInfoResponse.countDown', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='getEmployeTimes', full_name='protocal.game.LotteryProto.LotteryInfoResponse.getEmployeTimes', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=119,
  serialized_end=203,
)


_LOTTERYREQUEST = descriptor.Descriptor(
  name='LotteryRequest',
  full_name='protocal.game.LotteryProto.LotteryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='protocal.game.LotteryProto.LotteryRequest.type', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=205,
  serialized_end=235,
)


_LOTTERYRESPONSE = descriptor.Descriptor(
  name='LotteryResponse',
  full_name='protocal.game.LotteryProto.LotteryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='awardInfo', full_name='protocal.game.LotteryProto.LotteryResponse.awardInfo', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='employeList', full_name='protocal.game.LotteryProto.LotteryResponse.employeList', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='addItems', full_name='protocal.game.LotteryProto.LotteryResponse.addItems', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=238,
  serialized_end=424,
)


_AWARDINFO = descriptor.Descriptor(
  name='AwardInfo',
  full_name='protocal.game.LotteryProto.AwardInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='index', full_name='protocal.game.LotteryProto.AwardInfo.index', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='addItems', full_name='protocal.game.LotteryProto.AwardInfo.addItems', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='employes', full_name='protocal.game.LotteryProto.AwardInfo.employes', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='diamond', full_name='protocal.game.LotteryProto.AwardInfo.diamond', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=427,
  serialized_end=582,
)


_AWARDEMPLOYE = descriptor.Descriptor(
  name='AwardEmploye',
  full_name='protocal.game.LotteryProto.AwardEmploye',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='employeId', full_name='protocal.game.LotteryProto.AwardEmploye.employeId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='clothesId', full_name='protocal.game.LotteryProto.AwardEmploye.clothesId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=584,
  serialized_end=636,
)

_LOTTERYRESPONSE.fields_by_name['awardInfo'].message_type = _AWARDINFO
_LOTTERYRESPONSE.fields_by_name['employeList'].message_type = gameserver.protocol.Role_pb2._EMPLOYEINFO
_LOTTERYRESPONSE.fields_by_name['addItems'].message_type = gameserver.protocol.Role_pb2._BAGITEM
_AWARDINFO.fields_by_name['addItems'].message_type = gameserver.protocol.Role_pb2._BAGITEM
_AWARDINFO.fields_by_name['employes'].message_type = _AWARDEMPLOYE
DESCRIPTOR.message_types_by_name['LotteryInfoRequest'] = _LOTTERYINFOREQUEST
DESCRIPTOR.message_types_by_name['LotteryInfoResponse'] = _LOTTERYINFORESPONSE
DESCRIPTOR.message_types_by_name['LotteryRequest'] = _LOTTERYREQUEST
DESCRIPTOR.message_types_by_name['LotteryResponse'] = _LOTTERYRESPONSE
DESCRIPTOR.message_types_by_name['AwardInfo'] = _AWARDINFO
DESCRIPTOR.message_types_by_name['AwardEmploye'] = _AWARDEMPLOYE

class LotteryInfoRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOTTERYINFOREQUEST
  
  # @@protoc_insertion_point(class_scope:protocal.game.LotteryProto.LotteryInfoRequest)

class LotteryInfoResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOTTERYINFORESPONSE
  
  # @@protoc_insertion_point(class_scope:protocal.game.LotteryProto.LotteryInfoResponse)

class LotteryRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOTTERYREQUEST
  
  # @@protoc_insertion_point(class_scope:protocal.game.LotteryProto.LotteryRequest)

class LotteryResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOTTERYRESPONSE
  
  # @@protoc_insertion_point(class_scope:protocal.game.LotteryProto.LotteryResponse)

class AwardInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AWARDINFO
  
  # @@protoc_insertion_point(class_scope:protocal.game.LotteryProto.AwardInfo)

class AwardEmploye(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AWARDEMPLOYE
  
  # @@protoc_insertion_point(class_scope:protocal.game.LotteryProto.AwardEmploye)

# @@protoc_insertion_point(module_scope)
