# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='launch.protocol/Launch.proto',
  package='protocal.launch',
  serialized_pb='\n\x1claunch.protocol/Launch.proto\x12\x0fprotocal.launch\"N\n\rLaunchRequest\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x02(\t\x12\x0e\n\x06\x64\x65vice\x18\x03 \x02(\t\x12\n\n\x02ip\x18\x04 \x02(\t\"\xc4\x01\n\x0eLaunchResponse\x12\r\n\x05token\x18\x01 \x02(\t\x12\x0f\n\x07session\x18\x02 \x02(\t\x12\x0e\n\x06\x65xpire\x18\x03 \x02(\x03\x12\x0c\n\x04hash\x18\x04 \x02(\t\x12\r\n\x05isNew\x18\x05 \x02(\x08\x12\x30\n\x0bserversList\x18\x06 \x03(\x0b\x32\x1b.protocal.launch.ServerInfo\x12\x33\n\x0cmyServerList\x18\x07 \x03(\x0b\x32\x1d.protocal.launch.MyServerInfo\"!\n\nServerGate\x12\x13\n\x0bhostAddress\x18\x01 \x02(\t\"\x91\x01\n\nServerInfo\x12\x10\n\x08serverId\x18\x01 \x02(\x03\x12\x12\n\nserverName\x18\x02 \x02(\t\x12\x14\n\x0cserverStatus\x18\x03 \x02(\x05\x12\x12\n\nstatusInfo\x18\x04 \x01(\t\x12\x33\n\x0egateServerList\x18\x05 \x03(\x0b\x32\x1b.protocal.launch.ServerGate\"A\n\x0cMyServerInfo\x12\x10\n\x08serverId\x18\x01 \x02(\x03\x12\x10\n\x08nickName\x18\x02 \x02(\t\x12\r\n\x05level\x18\x03 \x02(\x05*.\n\x07ProtoID\x12\x0e\n\nLAUNCH_REQ\x10\x01\x12\x13\n\x0fLAUNCH_RESPONSE\x10\x02')

_PROTOID = descriptor.EnumDescriptor(
  name='ProtoID',
  full_name='protocal.launch.ProtoID',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='LAUNCH_REQ', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LAUNCH_RESPONSE', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=578,
  serialized_end=624,
)


LAUNCH_REQ = 1
LAUNCH_RESPONSE = 2



_LAUNCHREQUEST = descriptor.Descriptor(
  name='LaunchRequest',
  full_name='protocal.launch.LaunchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='account', full_name='protocal.launch.LaunchRequest.account', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='password', full_name='protocal.launch.LaunchRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='device', full_name='protocal.launch.LaunchRequest.device', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ip', full_name='protocal.launch.LaunchRequest.ip', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=49,
  serialized_end=127,
)


_LAUNCHRESPONSE = descriptor.Descriptor(
  name='LaunchResponse',
  full_name='protocal.launch.LaunchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='token', full_name='protocal.launch.LaunchResponse.token', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='session', full_name='protocal.launch.LaunchResponse.session', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='expire', full_name='protocal.launch.LaunchResponse.expire', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hash', full_name='protocal.launch.LaunchResponse.hash', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='isNew', full_name='protocal.launch.LaunchResponse.isNew', index=4,
      number=5, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='serversList', full_name='protocal.launch.LaunchResponse.serversList', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='myServerList', full_name='protocal.launch.LaunchResponse.myServerList', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=130,
  serialized_end=326,
)


_SERVERGATE = descriptor.Descriptor(
  name='ServerGate',
  full_name='protocal.launch.ServerGate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='hostAddress', full_name='protocal.launch.ServerGate.hostAddress', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=328,
  serialized_end=361,
)


_SERVERINFO = descriptor.Descriptor(
  name='ServerInfo',
  full_name='protocal.launch.ServerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='serverId', full_name='protocal.launch.ServerInfo.serverId', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='serverName', full_name='protocal.launch.ServerInfo.serverName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='serverStatus', full_name='protocal.launch.ServerInfo.serverStatus', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='statusInfo', full_name='protocal.launch.ServerInfo.statusInfo', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='gateServerList', full_name='protocal.launch.ServerInfo.gateServerList', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=364,
  serialized_end=509,
)


_MYSERVERINFO = descriptor.Descriptor(
  name='MyServerInfo',
  full_name='protocal.launch.MyServerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='serverId', full_name='protocal.launch.MyServerInfo.serverId', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='nickName', full_name='protocal.launch.MyServerInfo.nickName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='level', full_name='protocal.launch.MyServerInfo.level', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=511,
  serialized_end=576,
)

_LAUNCHRESPONSE.fields_by_name['serversList'].message_type = _SERVERINFO
_LAUNCHRESPONSE.fields_by_name['myServerList'].message_type = _MYSERVERINFO
_SERVERINFO.fields_by_name['gateServerList'].message_type = _SERVERGATE
DESCRIPTOR.message_types_by_name['LaunchRequest'] = _LAUNCHREQUEST
DESCRIPTOR.message_types_by_name['LaunchResponse'] = _LAUNCHRESPONSE
DESCRIPTOR.message_types_by_name['ServerGate'] = _SERVERGATE
DESCRIPTOR.message_types_by_name['ServerInfo'] = _SERVERINFO
DESCRIPTOR.message_types_by_name['MyServerInfo'] = _MYSERVERINFO

class LaunchRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LAUNCHREQUEST
  
  # @@protoc_insertion_point(class_scope:protocal.launch.LaunchRequest)

class LaunchResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LAUNCHRESPONSE
  
  # @@protoc_insertion_point(class_scope:protocal.launch.LaunchResponse)

class ServerGate(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SERVERGATE
  
  # @@protoc_insertion_point(class_scope:protocal.launch.ServerGate)

class ServerInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SERVERINFO
  
  # @@protoc_insertion_point(class_scope:protocal.launch.ServerInfo)

class MyServerInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MYSERVERINFO
  
  # @@protoc_insertion_point(class_scope:protocal.launch.MyServerInfo)

# @@protoc_insertion_point(module_scope)
