# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='gateserver.protocol/SystemIndex.proto',
  package='protocal.gate',
  serialized_pb='\n%gateserver.protocol/SystemIndex.proto\x12\rprotocal.gate*.\n\nSystemType\x12\x10\n\x0cSERVER_ERROR\x10\x01\x12\x0e\n\nHEART_BEAT\x10\x02')

_SYSTEMTYPE = descriptor.EnumDescriptor(
  name='SystemType',
  full_name='protocal.gate.SystemType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='SERVER_ERROR', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='HEART_BEAT', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=56,
  serialized_end=102,
)


SERVER_ERROR = 1
HEART_BEAT = 2



# @@protoc_insertion_point(module_scope)
