# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='GameSvrSystemIndex.proto',
  package='protocal.game',
  serialized_pb='\n\x18GameSvrSystemIndex.proto\x12\rprotocal.game*r\n\nSystemType\x12\x10\n\x0cSERVER_ERROR\x10\x01\x12\x15\n\x11GAMESVR_HEARTBEAT\x10\x02\x12\x08\n\x04ROLE\x10\x03\x12\t\n\x05STAGE\x10\x04\x12\r\n\tFORMATION\x10\x05\x12\x0b\n\x07\x45MPLOYE\x10\x06\x12\n\n\x06WEAPON\x10\x07')

_SYSTEMTYPE = descriptor.EnumDescriptor(
  name='SystemType',
  full_name='protocal.game.SystemType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='SERVER_ERROR', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAMESVR_HEARTBEAT', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ROLE', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STAGE', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FORMATION', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EMPLOYE', index=5, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='WEAPON', index=6, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=43,
  serialized_end=157,
)


SERVER_ERROR = 1
GAMESVR_HEARTBEAT = 2
ROLE = 3
STAGE = 4
FORMATION = 5
EMPLOYE = 6
WEAPON = 7



# @@protoc_insertion_point(module_scope)
