# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import gameserver.protocol.Role_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='gameserver.protocol/SignPro.proto',
  package='protocal.game.SignProto',
  serialized_pb='\n!gameserver.protocol/SignPro.proto\x12\x17protocal.game.SignProto\x1a\x1egameserver.protocol/Role.proto\"\x11\n\x0fSignInfoRequest\"p\n\x10SignInfoResponse\x12\x10\n\x08signDays\x18\x01 \x02(\x05\x12\x13\n\x0b\x61llSignDays\x18\x02 \x02(\x05\x12\r\n\x05group\x18\x03 \x02(\x05\x12\x13\n\x0bremedyTimes\x18\x04 \x02(\x05\x12\x11\n\ttodaySign\x18\x05 \x02(\x08\"\'\n\x0bSignRequest\x12\x18\n\x10\x63ostHardCuttency\x18\x01 \x02(\x05\"@\n\x0cSignResponse\x12\x30\n\x05\x61ward\x18\x01 \x02(\x0b\x32!.protocal.game.RoleProto.AwardPro*U\n\x07ProtoID\x12\x11\n\rSIGN_INFO_REQ\x10\x01\x12\x16\n\x12SIGN_INFO_RESPONSE\x10\x02\x12\x0c\n\x08SIGN_REQ\x10\x03\x12\x11\n\rSIGN_RESPONSE\x10\x04')

_PROTOID = descriptor.EnumDescriptor(
  name='ProtoID',
  full_name='protocal.game.SignProto.ProtoID',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='SIGN_INFO_REQ', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SIGN_INFO_RESPONSE', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SIGN_REQ', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SIGN_RESPONSE', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=334,
  serialized_end=419,
)


SIGN_INFO_REQ = 1
SIGN_INFO_RESPONSE = 2
SIGN_REQ = 3
SIGN_RESPONSE = 4



_SIGNINFOREQUEST = descriptor.Descriptor(
  name='SignInfoRequest',
  full_name='protocal.game.SignProto.SignInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=94,
  serialized_end=111,
)


_SIGNINFORESPONSE = descriptor.Descriptor(
  name='SignInfoResponse',
  full_name='protocal.game.SignProto.SignInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='signDays', full_name='protocal.game.SignProto.SignInfoResponse.signDays', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='allSignDays', full_name='protocal.game.SignProto.SignInfoResponse.allSignDays', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='group', full_name='protocal.game.SignProto.SignInfoResponse.group', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='remedyTimes', full_name='protocal.game.SignProto.SignInfoResponse.remedyTimes', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='todaySign', full_name='protocal.game.SignProto.SignInfoResponse.todaySign', index=4,
      number=5, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=113,
  serialized_end=225,
)


_SIGNREQUEST = descriptor.Descriptor(
  name='SignRequest',
  full_name='protocal.game.SignProto.SignRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='costHardCuttency', full_name='protocal.game.SignProto.SignRequest.costHardCuttency', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=227,
  serialized_end=266,
)


_SIGNRESPONSE = descriptor.Descriptor(
  name='SignResponse',
  full_name='protocal.game.SignProto.SignResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='award', full_name='protocal.game.SignProto.SignResponse.award', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=268,
  serialized_end=332,
)

_SIGNRESPONSE.fields_by_name['award'].message_type = gameserver.protocol.Role_pb2._AWARDPRO
DESCRIPTOR.message_types_by_name['SignInfoRequest'] = _SIGNINFOREQUEST
DESCRIPTOR.message_types_by_name['SignInfoResponse'] = _SIGNINFORESPONSE
DESCRIPTOR.message_types_by_name['SignRequest'] = _SIGNREQUEST
DESCRIPTOR.message_types_by_name['SignResponse'] = _SIGNRESPONSE

class SignInfoRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SIGNINFOREQUEST
  
  # @@protoc_insertion_point(class_scope:protocal.game.SignProto.SignInfoRequest)

class SignInfoResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SIGNINFORESPONSE
  
  # @@protoc_insertion_point(class_scope:protocal.game.SignProto.SignInfoResponse)

class SignRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SIGNREQUEST
  
  # @@protoc_insertion_point(class_scope:protocal.game.SignProto.SignRequest)

class SignResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SIGNRESPONSE
  
  # @@protoc_insertion_point(class_scope:protocal.game.SignProto.SignResponse)

# @@protoc_insertion_point(module_scope)
