# Generated by the pb_protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='gameserver.pb_protocol/Formation.proto',
  package='protocal.game.FormationProto',
  serialized_pb='\n#gameserver.pb_protocol/Formation.proto\x12\x1cprotocal.game.FormationProto\",\n\x14\x46ormationInfoRequest\x12\x14\n\x0c\x66ormationNum\x18\x01 \x02(\x05\"_\n\x15\x46ormationInfoResponse\x12\x46\n\x11\x62\x61ttleEmployeList\x18\x01 \x03(\x0b\x32+.protocal.game.FormationProto.BattleEmploye\"2\n\rBattleEmploye\x12\x12\n\nemployeUid\x18\x01 \x02(\x03\x12\r\n\x05index\x18\x02 \x02(\x05\"7\n\x12\x46ormationUpRequest\x12\x12\n\nemployeUid\x18\x01 \x02(\x03\x12\r\n\x05index\x18\x02 \x02(\x05\"\x15\n\x13\x46ormationUpResponse\"*\n\x14\x46ormationDownRequest\x12\x12\n\nemployeUid\x18\x01 \x02(\x03\"\x17\n\x15\x46ormationDownResponse*\xa4\x01\n\x07ProtoID\x12\x16\n\x12\x46ORMATION_INFO_REQ\x10\x01\x12\x1b\n\x17\x46ORMATION_INFO_RESPONSE\x10\x02\x12\x14\n\x10\x46ORMATION_UP_REQ\x10\x03\x12\x19\n\x15\x46ORMATION_UP_RESPONSE\x10\x04\x12\x16\n\x12\x46ORMATION_DOWN_REQ\x10\x05\x12\x1b\n\x17\x46ORMATION_DOWN_RESPONSE\x10\x06')

_PROTOID = descriptor.EnumDescriptor(
  name='ProtoID',
  full_name='protocal.game.FormationProto.ProtoID',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='FORMATION_INFO_REQ', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FORMATION_INFO_RESPONSE', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FORMATION_UP_REQ', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FORMATION_UP_RESPONSE', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FORMATION_DOWN_REQ', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FORMATION_DOWN_RESPONSE', index=5, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=414,
  serialized_end=578,
)


FORMATION_INFO_REQ = 1
FORMATION_INFO_RESPONSE = 2
FORMATION_UP_REQ = 3
FORMATION_UP_RESPONSE = 4
FORMATION_DOWN_REQ = 5
FORMATION_DOWN_RESPONSE = 6



_FORMATIONINFOREQUEST = descriptor.Descriptor(
  name='FormationInfoRequest',
  full_name='protocal.game.FormationProto.FormationInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='formationNum', full_name='protocal.game.FormationProto.FormationInfoRequest.formationNum', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=69,
  serialized_end=113,
)


_FORMATIONINFORESPONSE = descriptor.Descriptor(
  name='FormationInfoResponse',
  full_name='protocal.game.FormationProto.FormationInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='battleEmployeList', full_name='protocal.game.FormationProto.FormationInfoResponse.battleEmployeList', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=115,
  serialized_end=210,
)


_BATTLEEMPLOYE = descriptor.Descriptor(
  name='BattleEmploye',
  full_name='protocal.game.FormationProto.BattleEmploye',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='employeUid', full_name='protocal.game.FormationProto.BattleEmploye.employeUid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='index', full_name='protocal.game.FormationProto.BattleEmploye.index', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=212,
  serialized_end=262,
)


_FORMATIONUPREQUEST = descriptor.Descriptor(
  name='FormationUpRequest',
  full_name='protocal.game.FormationProto.FormationUpRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='employeUid', full_name='protocal.game.FormationProto.FormationUpRequest.employeUid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='index', full_name='protocal.game.FormationProto.FormationUpRequest.index', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=264,
  serialized_end=319,
)


_FORMATIONUPRESPONSE = descriptor.Descriptor(
  name='FormationUpResponse',
  full_name='protocal.game.FormationProto.FormationUpResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=321,
  serialized_end=342,
)


_FORMATIONDOWNREQUEST = descriptor.Descriptor(
  name='FormationDownRequest',
  full_name='protocal.game.FormationProto.FormationDownRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='employeUid', full_name='protocal.game.FormationProto.FormationDownRequest.employeUid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=344,
  serialized_end=386,
)


_FORMATIONDOWNRESPONSE = descriptor.Descriptor(
  name='FormationDownResponse',
  full_name='protocal.game.FormationProto.FormationDownResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=388,
  serialized_end=411,
)

_FORMATIONINFORESPONSE.fields_by_name['battleEmployeList'].message_type = _BATTLEEMPLOYE
DESCRIPTOR.message_types_by_name['FormationInfoRequest'] = _FORMATIONINFOREQUEST
DESCRIPTOR.message_types_by_name['FormationInfoResponse'] = _FORMATIONINFORESPONSE
DESCRIPTOR.message_types_by_name['BattleEmploye'] = _BATTLEEMPLOYE
DESCRIPTOR.message_types_by_name['FormationUpRequest'] = _FORMATIONUPREQUEST
DESCRIPTOR.message_types_by_name['FormationUpResponse'] = _FORMATIONUPRESPONSE
DESCRIPTOR.message_types_by_name['FormationDownRequest'] = _FORMATIONDOWNREQUEST
DESCRIPTOR.message_types_by_name['FormationDownResponse'] = _FORMATIONDOWNRESPONSE

class FormationInfoRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FORMATIONINFOREQUEST
  
  # @@protoc_insertion_point(class_scope:protocal.game.FormationProto.FormationInfoRequest)

class FormationInfoResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FORMATIONINFORESPONSE
  
  # @@protoc_insertion_point(class_scope:protocal.game.FormationProto.FormationInfoResponse)

class BattleEmploye(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BATTLEEMPLOYE
  
  # @@protoc_insertion_point(class_scope:protocal.game.FormationProto.BattleEmploye)

class FormationUpRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FORMATIONUPREQUEST
  
  # @@protoc_insertion_point(class_scope:protocal.game.FormationProto.FormationUpRequest)

class FormationUpResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FORMATIONUPRESPONSE
  
  # @@protoc_insertion_point(class_scope:protocal.game.FormationProto.FormationUpResponse)

class FormationDownRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FORMATIONDOWNREQUEST
  
  # @@protoc_insertion_point(class_scope:protocal.game.FormationProto.FormationDownRequest)

class FormationDownResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FORMATIONDOWNRESPONSE
  
  # @@protoc_insertion_point(class_scope:protocal.game.FormationProto.FormationDownResponse)

# @@protoc_insertion_point(module_scope)
