# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='ServerError.proto',
  package='commonProtocal.JokerServerProto',
  serialized_pb='\n\x11ServerError.proto\x12\x1f\x63ommonProtocal.JokerServerProto\"2\n\x0fServerException\x12\x11\n\terrorCode\x18\x01 \x02(\r\x12\x0c\n\x04info\x18\x02 \x02(\t*\x1f\n\x07ProtoID\x12\x14\n\x10SERVER_EXCEPTION\x10\x01')

_PROTOID = descriptor.EnumDescriptor(
  name='ProtoID',
  full_name='commonProtocal.JokerServerProto.ProtoID',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='SERVER_EXCEPTION', index=0, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=106,
  serialized_end=137,
)


SERVER_EXCEPTION = 1



_SERVEREXCEPTION = descriptor.Descriptor(
  name='ServerException',
  full_name='commonProtocal.JokerServerProto.ServerException',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='errorCode', full_name='commonProtocal.JokerServerProto.ServerException.errorCode', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='info', full_name='commonProtocal.JokerServerProto.ServerException.info', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=54,
  serialized_end=104,
)

DESCRIPTOR.message_types_by_name['ServerException'] = _SERVEREXCEPTION

class ServerException(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SERVEREXCEPTION
  
  # @@protoc_insertion_point(class_scope:commonProtocal.JokerServerProto.ServerException)

# @@protoc_insertion_point(module_scope)
