# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='weaponPro.proto',
  package='protocal.game.WeaponProto',
  serialized_pb='\n\x0fweaponPro.proto\x12\x19protocal.game.WeaponProto\")\n\x14WeaponUpgradeRequest\x12\x11\n\tweaponUid\x18\x01 \x02(\x03\"\x17\n\x15WeaponUpgradeResponse\")\n\x14WeaponAdvanceRequest\x12\x11\n\tweaponUid\x18\x01 \x02(\x03\"\x17\n\x15WeaponAdvanceResponse\"=\n\x14WeaponReplaceRequest\x12\x11\n\tweaponUid\x18\x01 \x02(\x03\x12\x12\n\nemployeUid\x18\x02 \x02(\x03\"\x17\n\x15WeaponReplaceResponse*\xa8\x01\n\x07ProtoID\x12\x16\n\x12WEAPON_UPGRADE_REQ\x10\x01\x12\x1b\n\x17WEAPON_UPGRADE_RESPINSE\x10\x02\x12\x16\n\x12WEAPON_ADVANCE_REQ\x10\x03\x12\x1b\n\x17WEAPON_ADVANCE_RESPINSE\x10\x04\x12\x16\n\x12WEAPON_REPLACE_REQ\x10\x05\x12\x1b\n\x17WEAPON_REPLACE_RESPINSE\x10\x06')

_PROTOID = descriptor.EnumDescriptor(
  name='ProtoID',
  full_name='protocal.game.WeaponProto.ProtoID',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='WEAPON_UPGRADE_REQ', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='WEAPON_UPGRADE_RESPINSE', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='WEAPON_ADVANCE_REQ', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='WEAPON_ADVANCE_RESPINSE', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='WEAPON_REPLACE_REQ', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='WEAPON_REPLACE_RESPINSE', index=5, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=271,
  serialized_end=439,
)


WEAPON_UPGRADE_REQ = 1
WEAPON_UPGRADE_RESPINSE = 2
WEAPON_ADVANCE_REQ = 3
WEAPON_ADVANCE_RESPINSE = 4
WEAPON_REPLACE_REQ = 5
WEAPON_REPLACE_RESPINSE = 6



_WEAPONUPGRADEREQUEST = descriptor.Descriptor(
  name='WeaponUpgradeRequest',
  full_name='protocal.game.WeaponProto.WeaponUpgradeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='weaponUid', full_name='protocal.game.WeaponProto.WeaponUpgradeRequest.weaponUid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=46,
  serialized_end=87,
)


_WEAPONUPGRADERESPONSE = descriptor.Descriptor(
  name='WeaponUpgradeResponse',
  full_name='protocal.game.WeaponProto.WeaponUpgradeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=89,
  serialized_end=112,
)


_WEAPONADVANCEREQUEST = descriptor.Descriptor(
  name='WeaponAdvanceRequest',
  full_name='protocal.game.WeaponProto.WeaponAdvanceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='weaponUid', full_name='protocal.game.WeaponProto.WeaponAdvanceRequest.weaponUid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=114,
  serialized_end=155,
)


_WEAPONADVANCERESPONSE = descriptor.Descriptor(
  name='WeaponAdvanceResponse',
  full_name='protocal.game.WeaponProto.WeaponAdvanceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=157,
  serialized_end=180,
)


_WEAPONREPLACEREQUEST = descriptor.Descriptor(
  name='WeaponReplaceRequest',
  full_name='protocal.game.WeaponProto.WeaponReplaceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='weaponUid', full_name='protocal.game.WeaponProto.WeaponReplaceRequest.weaponUid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='employeUid', full_name='protocal.game.WeaponProto.WeaponReplaceRequest.employeUid', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=182,
  serialized_end=243,
)


_WEAPONREPLACERESPONSE = descriptor.Descriptor(
  name='WeaponReplaceResponse',
  full_name='protocal.game.WeaponProto.WeaponReplaceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=245,
  serialized_end=268,
)

DESCRIPTOR.message_types_by_name['WeaponUpgradeRequest'] = _WEAPONUPGRADEREQUEST
DESCRIPTOR.message_types_by_name['WeaponUpgradeResponse'] = _WEAPONUPGRADERESPONSE
DESCRIPTOR.message_types_by_name['WeaponAdvanceRequest'] = _WEAPONADVANCEREQUEST
DESCRIPTOR.message_types_by_name['WeaponAdvanceResponse'] = _WEAPONADVANCERESPONSE
DESCRIPTOR.message_types_by_name['WeaponReplaceRequest'] = _WEAPONREPLACEREQUEST
DESCRIPTOR.message_types_by_name['WeaponReplaceResponse'] = _WEAPONREPLACERESPONSE

class WeaponUpgradeRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WEAPONUPGRADEREQUEST
  
  # @@protoc_insertion_point(class_scope:protocal.game.WeaponProto.WeaponUpgradeRequest)

class WeaponUpgradeResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WEAPONUPGRADERESPONSE
  
  # @@protoc_insertion_point(class_scope:protocal.game.WeaponProto.WeaponUpgradeResponse)

class WeaponAdvanceRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WEAPONADVANCEREQUEST
  
  # @@protoc_insertion_point(class_scope:protocal.game.WeaponProto.WeaponAdvanceRequest)

class WeaponAdvanceResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WEAPONADVANCERESPONSE
  
  # @@protoc_insertion_point(class_scope:protocal.game.WeaponProto.WeaponAdvanceResponse)

class WeaponReplaceRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WEAPONREPLACEREQUEST
  
  # @@protoc_insertion_point(class_scope:protocal.game.WeaponProto.WeaponReplaceRequest)

class WeaponReplaceResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WEAPONREPLACERESPONSE
  
  # @@protoc_insertion_point(class_scope:protocal.game.WeaponProto.WeaponReplaceResponse)

# @@protoc_insertion_point(module_scope)
