# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WorldClockProtocol.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WorldClockProtocol.proto',
  package='protocal',
  serialized_pb='\n\x18WorldClockProtocol.proto\x12\x08protocal\"@\n\x08Location\x12&\n\tcontinent\x18\x01 \x02(\x0e\x32\x13.protocal.Continent\x12\x0c\n\x04\x63ity\x18\x02 \x02(\t\"1\n\tLocations\x12$\n\x08location\x18\x01 \x03(\x0b\x32\x12.protocal.Location\"\x92\x01\n\tLocalTime\x12\x0c\n\x04year\x18\x01 \x02(\r\x12\r\n\x05month\x18\x02 \x02(\r\x12\x12\n\ndayOfMonth\x18\x04 \x02(\r\x12&\n\tdayOfWeek\x18\x05 \x02(\x0e\x32\x13.protocal.DayOfWeek\x12\x0c\n\x04hour\x18\x06 \x02(\r\x12\x0e\n\x06minute\x18\x07 \x02(\r\x12\x0e\n\x06second\x18\x08 \x02(\r\"4\n\nLocalTimes\x12&\n\tlocalTime\x18\x01 \x03(\x0b\x32\x13.protocal.LocalTime*\x99\x01\n\tContinent\x12\n\n\x06\x41\x46RICA\x10\x00\x12\x0b\n\x07\x41MERICA\x10\x01\x12\x0e\n\nANTARCTICA\x10\x02\x12\n\n\x06\x41RCTIC\x10\x03\x12\x08\n\x04\x41SIA\x10\x04\x12\x0c\n\x08\x41TLANTIC\x10\x05\x12\r\n\tAUSTRALIA\x10\x06\x12\n\n\x06\x45UROPE\x10\x07\x12\n\n\x06INDIAN\x10\x08\x12\x0b\n\x07MIDEAST\x10\t\x12\x0b\n\x07PACIFIC\x10\n*g\n\tDayOfWeek\x12\n\n\x06SUNDAY\x10\x01\x12\n\n\x06MONDAY\x10\x02\x12\x0b\n\x07TUESDAY\x10\x03\x12\r\n\tWEDNESDAY\x10\x04\x12\x0c\n\x08THURSDAY\x10\x05\x12\n\n\x06\x46RIDAY\x10\x06\x12\x0c\n\x08SATURDAY\x10\x07\x42\x02H\x01')

_CONTINENT = _descriptor.EnumDescriptor(
  name='Continent',
  full_name='protocal.Continent',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AFRICA', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AMERICA', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANTARCTICA', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ARCTIC', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ASIA', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ATLANTIC', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUSTRALIA', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EUROPE', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INDIAN', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MIDEAST', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PACIFIC', index=10, number=10,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=359,
  serialized_end=512,
)

Continent = enum_type_wrapper.EnumTypeWrapper(_CONTINENT)
_DAYOFWEEK = _descriptor.EnumDescriptor(
  name='DayOfWeek',
  full_name='protocal.DayOfWeek',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUNDAY', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MONDAY', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TUESDAY', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WEDNESDAY', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='THURSDAY', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FRIDAY', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SATURDAY', index=6, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=514,
  serialized_end=617,
)

DayOfWeek = enum_type_wrapper.EnumTypeWrapper(_DAYOFWEEK)
AFRICA = 0
AMERICA = 1
ANTARCTICA = 2
ARCTIC = 3
ASIA = 4
ATLANTIC = 5
AUSTRALIA = 6
EUROPE = 7
INDIAN = 8
MIDEAST = 9
PACIFIC = 10
SUNDAY = 1
MONDAY = 2
TUESDAY = 3
WEDNESDAY = 4
THURSDAY = 5
FRIDAY = 6
SATURDAY = 7



_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='protocal.Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='continent', full_name='protocal.Location.continent', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='city', full_name='protocal.Location.city', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=38,
  serialized_end=102,
)


_LOCATIONS = _descriptor.Descriptor(
  name='Locations',
  full_name='protocal.Locations',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='protocal.Locations.location', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=104,
  serialized_end=153,
)


_LOCALTIME = _descriptor.Descriptor(
  name='LocalTime',
  full_name='protocal.LocalTime',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='year', full_name='protocal.LocalTime.year', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='month', full_name='protocal.LocalTime.month', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dayOfMonth', full_name='protocal.LocalTime.dayOfMonth', index=2,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dayOfWeek', full_name='protocal.LocalTime.dayOfWeek', index=3,
      number=5, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hour', full_name='protocal.LocalTime.hour', index=4,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minute', full_name='protocal.LocalTime.minute', index=5,
      number=7, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='second', full_name='protocal.LocalTime.second', index=6,
      number=8, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=156,
  serialized_end=302,
)


_LOCALTIMES = _descriptor.Descriptor(
  name='LocalTimes',
  full_name='protocal.LocalTimes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='localTime', full_name='protocal.LocalTimes.localTime', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=304,
  serialized_end=356,
)

_LOCATION.fields_by_name['continent'].enum_type = _CONTINENT
_LOCATIONS.fields_by_name['location'].message_type = _LOCATION
_LOCALTIME.fields_by_name['dayOfWeek'].enum_type = _DAYOFWEEK
_LOCALTIMES.fields_by_name['localTime'].message_type = _LOCALTIME
DESCRIPTOR.message_types_by_name['Location'] = _LOCATION
DESCRIPTOR.message_types_by_name['Locations'] = _LOCATIONS
DESCRIPTOR.message_types_by_name['LocalTime'] = _LOCALTIME
DESCRIPTOR.message_types_by_name['LocalTimes'] = _LOCALTIMES

class Location(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOCATION

  # @@protoc_insertion_point(class_scope:protocal.Location)

class Locations(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOCATIONS

  # @@protoc_insertion_point(class_scope:protocal.Locations)

class LocalTime(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOCALTIME

  # @@protoc_insertion_point(class_scope:protocal.LocalTime)

class LocalTimes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOCALTIMES

  # @@protoc_insertion_point(class_scope:protocal.LocalTimes)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'H\001')
# @@protoc_insertion_point(module_scope)
