# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import gameserver.protocol.Role_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='gameserver.protocol/EmployeSys.proto',
  package='protocal.game.EmployeProto',
  serialized_pb='\n$gameserver.protocol/EmployeSys.proto\x12\x1aprotocal.game.EmployeProto\x1a\x1egameserver.protocol/Role.proto\"F\n\x15\x45mployeUpgradeRequest\x12\x12\n\nemployeUid\x18\x01 \x02(\x03\x12\n\n\x02id\x18\x02 \x02(\x05\x12\r\n\x05\x63ount\x18\x03 \x02(\x05\"4\n\x16\x45mployeUpgradeResponse\x12\r\n\x05level\x18\x01 \x02(\x05\x12\x0b\n\x03\x65xp\x18\x02 \x02(\x05\"+\n\x15\x45mployeAdvanceRequest\x12\x12\n\nemployeUid\x18\x01 \x02(\x03\"\'\n\x16\x45mployeAdvanceResponse\x12\r\n\x05isSuc\x18\x01 \x02(\x08\"*\n\x14\x45mployeUpStarRequest\x12\x12\n\nemployeUid\x18\x01 \x02(\x03\"&\n\x15\x45mployeUpStarResponse\x12\r\n\x05isSuc\x18\x01 \x02(\x08\"=\n\x16\x41ssistEmployeUpRequest\x12\x12\n\nemployeUid\x18\x01 \x02(\x03\x12\x0f\n\x07\x64ownUid\x18\x02 \x02(\x03\"\x19\n\x17\x41ssistEmployeUpResponse\".\n\x18\x41ssistEmployeDownRequest\x12\x12\n\nemployeUid\x18\x01 \x02(\x03\"\x1b\n\x19\x41ssistEmployeDownResponse\"N\n\x16\x45mployeCompoundRequest\x12\x11\n\temployeId\x18\x01 \x02(\x05\x12\x0e\n\x06itemId\x18\x02 \x02(\x05\x12\x11\n\titemCount\x18\x03 \x02(\x05\"S\n\x17\x45mployeCompoundResponse\x12\x38\n\nnewEmploye\x18\x01 \x02(\x0b\x32$.protocal.game.RoleProto.EmployeInfo*\xe1\x02\n\x07ProtoID\x12\x17\n\x13\x45MPLOYE_UPGRADE_REQ\x10\x01\x12\x1c\n\x18\x45MPLOYE_UPGRADE_RESPONSE\x10\x02\x12\x17\n\x13\x45MPLOYE_ADVANCE_REQ\x10\x03\x12\x1c\n\x18\x45MPLOYE_ADVANCE_RESPONSE\x10\x04\x12\x17\n\x13\x45MPLOYE_UP_STAR_REQ\x10\x05\x12\x1c\n\x18\x45MPLOYE_UP_STAR_RESPONSE\x10\x06\x12\x19\n\x15\x45MPLOYE_ASSIST_UP_REQ\x10\x07\x12\x1e\n\x1a\x45MPLOYE_ASSIST_UP_RESPONSE\x10\x08\x12\x1b\n\x17\x45MPLOYE_ASSIST_DOWN_REQ\x10\t\x12 \n\x1c\x45MPLOYE_ASSIST_DOWN_RESPONSE\x10\n\x12\x18\n\x14\x45MPLOYE_COMPOUND_REQ\x10\x0b\x12\x1d\n\x19\x45MPLOYE_COMPOUND_RESPONSE\x10\x0c')

_PROTOID = descriptor.EnumDescriptor(
  name='ProtoID',
  full_name='protocal.game.EmployeProto.ProtoID',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='EMPLOYE_UPGRADE_REQ', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EMPLOYE_UPGRADE_RESPONSE', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EMPLOYE_ADVANCE_REQ', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EMPLOYE_ADVANCE_RESPONSE', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EMPLOYE_UP_STAR_REQ', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EMPLOYE_UP_STAR_RESPONSE', index=5, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EMPLOYE_ASSIST_UP_REQ', index=6, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EMPLOYE_ASSIST_UP_RESPONSE', index=7, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EMPLOYE_ASSIST_DOWN_REQ', index=8, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EMPLOYE_ASSIST_DOWN_RESPONSE', index=9, number=10,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EMPLOYE_COMPOUND_REQ', index=10, number=11,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EMPLOYE_COMPOUND_RESPONSE', index=11, number=12,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=729,
  serialized_end=1082,
)


EMPLOYE_UPGRADE_REQ = 1
EMPLOYE_UPGRADE_RESPONSE = 2
EMPLOYE_ADVANCE_REQ = 3
EMPLOYE_ADVANCE_RESPONSE = 4
EMPLOYE_UP_STAR_REQ = 5
EMPLOYE_UP_STAR_RESPONSE = 6
EMPLOYE_ASSIST_UP_REQ = 7
EMPLOYE_ASSIST_UP_RESPONSE = 8
EMPLOYE_ASSIST_DOWN_REQ = 9
EMPLOYE_ASSIST_DOWN_RESPONSE = 10
EMPLOYE_COMPOUND_REQ = 11
EMPLOYE_COMPOUND_RESPONSE = 12



_EMPLOYEUPGRADEREQUEST = descriptor.Descriptor(
  name='EmployeUpgradeRequest',
  full_name='protocal.game.EmployeProto.EmployeUpgradeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='employeUid', full_name='protocal.game.EmployeProto.EmployeUpgradeRequest.employeUid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='id', full_name='protocal.game.EmployeProto.EmployeUpgradeRequest.id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='count', full_name='protocal.game.EmployeProto.EmployeUpgradeRequest.count', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=100,
  serialized_end=170,
)


_EMPLOYEUPGRADERESPONSE = descriptor.Descriptor(
  name='EmployeUpgradeResponse',
  full_name='protocal.game.EmployeProto.EmployeUpgradeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='level', full_name='protocal.game.EmployeProto.EmployeUpgradeResponse.level', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='exp', full_name='protocal.game.EmployeProto.EmployeUpgradeResponse.exp', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=172,
  serialized_end=224,
)


_EMPLOYEADVANCEREQUEST = descriptor.Descriptor(
  name='EmployeAdvanceRequest',
  full_name='protocal.game.EmployeProto.EmployeAdvanceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='employeUid', full_name='protocal.game.EmployeProto.EmployeAdvanceRequest.employeUid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=226,
  serialized_end=269,
)


_EMPLOYEADVANCERESPONSE = descriptor.Descriptor(
  name='EmployeAdvanceResponse',
  full_name='protocal.game.EmployeProto.EmployeAdvanceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='isSuc', full_name='protocal.game.EmployeProto.EmployeAdvanceResponse.isSuc', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=271,
  serialized_end=310,
)


_EMPLOYEUPSTARREQUEST = descriptor.Descriptor(
  name='EmployeUpStarRequest',
  full_name='protocal.game.EmployeProto.EmployeUpStarRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='employeUid', full_name='protocal.game.EmployeProto.EmployeUpStarRequest.employeUid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=312,
  serialized_end=354,
)


_EMPLOYEUPSTARRESPONSE = descriptor.Descriptor(
  name='EmployeUpStarResponse',
  full_name='protocal.game.EmployeProto.EmployeUpStarResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='isSuc', full_name='protocal.game.EmployeProto.EmployeUpStarResponse.isSuc', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=356,
  serialized_end=394,
)


_ASSISTEMPLOYEUPREQUEST = descriptor.Descriptor(
  name='AssistEmployeUpRequest',
  full_name='protocal.game.EmployeProto.AssistEmployeUpRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='employeUid', full_name='protocal.game.EmployeProto.AssistEmployeUpRequest.employeUid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='downUid', full_name='protocal.game.EmployeProto.AssistEmployeUpRequest.downUid', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=396,
  serialized_end=457,
)


_ASSISTEMPLOYEUPRESPONSE = descriptor.Descriptor(
  name='AssistEmployeUpResponse',
  full_name='protocal.game.EmployeProto.AssistEmployeUpResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=459,
  serialized_end=484,
)


_ASSISTEMPLOYEDOWNREQUEST = descriptor.Descriptor(
  name='AssistEmployeDownRequest',
  full_name='protocal.game.EmployeProto.AssistEmployeDownRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='employeUid', full_name='protocal.game.EmployeProto.AssistEmployeDownRequest.employeUid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=486,
  serialized_end=532,
)


_ASSISTEMPLOYEDOWNRESPONSE = descriptor.Descriptor(
  name='AssistEmployeDownResponse',
  full_name='protocal.game.EmployeProto.AssistEmployeDownResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=534,
  serialized_end=561,
)


_EMPLOYECOMPOUNDREQUEST = descriptor.Descriptor(
  name='EmployeCompoundRequest',
  full_name='protocal.game.EmployeProto.EmployeCompoundRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='employeId', full_name='protocal.game.EmployeProto.EmployeCompoundRequest.employeId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='itemId', full_name='protocal.game.EmployeProto.EmployeCompoundRequest.itemId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='itemCount', full_name='protocal.game.EmployeProto.EmployeCompoundRequest.itemCount', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=563,
  serialized_end=641,
)


_EMPLOYECOMPOUNDRESPONSE = descriptor.Descriptor(
  name='EmployeCompoundResponse',
  full_name='protocal.game.EmployeProto.EmployeCompoundResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='newEmploye', full_name='protocal.game.EmployeProto.EmployeCompoundResponse.newEmploye', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=643,
  serialized_end=726,
)

_EMPLOYECOMPOUNDRESPONSE.fields_by_name['newEmploye'].message_type = gameserver.protocol.Role_pb2._EMPLOYEINFO
DESCRIPTOR.message_types_by_name['EmployeUpgradeRequest'] = _EMPLOYEUPGRADEREQUEST
DESCRIPTOR.message_types_by_name['EmployeUpgradeResponse'] = _EMPLOYEUPGRADERESPONSE
DESCRIPTOR.message_types_by_name['EmployeAdvanceRequest'] = _EMPLOYEADVANCEREQUEST
DESCRIPTOR.message_types_by_name['EmployeAdvanceResponse'] = _EMPLOYEADVANCERESPONSE
DESCRIPTOR.message_types_by_name['EmployeUpStarRequest'] = _EMPLOYEUPSTARREQUEST
DESCRIPTOR.message_types_by_name['EmployeUpStarResponse'] = _EMPLOYEUPSTARRESPONSE
DESCRIPTOR.message_types_by_name['AssistEmployeUpRequest'] = _ASSISTEMPLOYEUPREQUEST
DESCRIPTOR.message_types_by_name['AssistEmployeUpResponse'] = _ASSISTEMPLOYEUPRESPONSE
DESCRIPTOR.message_types_by_name['AssistEmployeDownRequest'] = _ASSISTEMPLOYEDOWNREQUEST
DESCRIPTOR.message_types_by_name['AssistEmployeDownResponse'] = _ASSISTEMPLOYEDOWNRESPONSE
DESCRIPTOR.message_types_by_name['EmployeCompoundRequest'] = _EMPLOYECOMPOUNDREQUEST
DESCRIPTOR.message_types_by_name['EmployeCompoundResponse'] = _EMPLOYECOMPOUNDRESPONSE

class EmployeUpgradeRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EMPLOYEUPGRADEREQUEST
  
  # @@protoc_insertion_point(class_scope:protocal.game.EmployeProto.EmployeUpgradeRequest)

class EmployeUpgradeResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EMPLOYEUPGRADERESPONSE
  
  # @@protoc_insertion_point(class_scope:protocal.game.EmployeProto.EmployeUpgradeResponse)

class EmployeAdvanceRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EMPLOYEADVANCEREQUEST
  
  # @@protoc_insertion_point(class_scope:protocal.game.EmployeProto.EmployeAdvanceRequest)

class EmployeAdvanceResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EMPLOYEADVANCERESPONSE
  
  # @@protoc_insertion_point(class_scope:protocal.game.EmployeProto.EmployeAdvanceResponse)

class EmployeUpStarRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EMPLOYEUPSTARREQUEST
  
  # @@protoc_insertion_point(class_scope:protocal.game.EmployeProto.EmployeUpStarRequest)

class EmployeUpStarResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EMPLOYEUPSTARRESPONSE
  
  # @@protoc_insertion_point(class_scope:protocal.game.EmployeProto.EmployeUpStarResponse)

class AssistEmployeUpRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ASSISTEMPLOYEUPREQUEST
  
  # @@protoc_insertion_point(class_scope:protocal.game.EmployeProto.AssistEmployeUpRequest)

class AssistEmployeUpResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ASSISTEMPLOYEUPRESPONSE
  
  # @@protoc_insertion_point(class_scope:protocal.game.EmployeProto.AssistEmployeUpResponse)

class AssistEmployeDownRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ASSISTEMPLOYEDOWNREQUEST
  
  # @@protoc_insertion_point(class_scope:protocal.game.EmployeProto.AssistEmployeDownRequest)

class AssistEmployeDownResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ASSISTEMPLOYEDOWNRESPONSE
  
  # @@protoc_insertion_point(class_scope:protocal.game.EmployeProto.AssistEmployeDownResponse)

class EmployeCompoundRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EMPLOYECOMPOUNDREQUEST
  
  # @@protoc_insertion_point(class_scope:protocal.game.EmployeProto.EmployeCompoundRequest)

class EmployeCompoundResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EMPLOYECOMPOUNDRESPONSE
  
  # @@protoc_insertion_point(class_scope:protocal.game.EmployeProto.EmployeCompoundResponse)

# @@protoc_insertion_point(module_scope)
