# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='gameserver.protocol/MailPro.proto',
  package='protocal.game.MailProto',
  serialized_pb='\n!gameserver.protocol/MailPro.proto\x12\x17protocal.game.MailProto\"\x92\x01\n\x08MailInfo\x12\x0e\n\x06mailId\x18\x01 \x02(\x05\x12\r\n\x05title\x18\x02 \x02(\t\x12\x0e\n\x06sender\x18\x03 \x02(\t\x12\x0c\n\x04icon\x18\x04 \x02(\t\x12\x10\n\x08\x63ontents\x18\x05 \x02(\t\x12\x13\n\x0b\x63reatedTime\x18\x06 \x02(\t\x12\x0e\n\x06status\x18\x07 \x02(\x05\x12\x12\n\nattachment\x18\x08 \x01(\t\"D\n\x0fMailListRequest\x12\x0c\n\x04page\x18\x01 \x02(\x05\x12\x12\n\nnumPerPage\x18\x02 \x02(\x05\x12\x0f\n\x07pageNum\x18\x03 \x02(\x05\"g\n\x10MailListResponse\x12\x0f\n\x07maxPage\x18\x01 \x02(\x05\x12\x30\n\x05mails\x18\x02 \x03(\x0b\x32!.protocal.game.MailProto.MailInfo\x12\x10\n\x08isOneKey\x18\x03 \x02(\x08\"+\n\x19GetMailAttachmentsRequest\x12\x0e\n\x06mailId\x18\x01 \x02(\x05\",\n\x1aGetMailAttachmentsResponse\x12\x0e\n\x06status\x18\x01 \x02(\x08\"\x17\n\x15GetAttachmentsRequest\"A\n\x0e\x41ttachmentInfo\x12\r\n\x05title\x18\x01 \x02(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x02(\t\x12\x12\n\nattachment\x18\x03 \x02(\t\"f\n\x16GetAttachmentsResponse\x12\x0e\n\x06status\x18\x01 \x02(\x08\x12<\n\x0b\x61ttachments\x18\x02 \x03(\x0b\x32\'.protocal.game.MailProto.AttachmentInfo\"!\n\x0fReadMailRequest\x12\x0e\n\x06mailId\x18\x01 \x02(\x05\"\"\n\x10ReadMailResponse\x12\x0e\n\x06status\x18\x01 \x02(\x08*\xd6\x01\n\x07ProtoID\x12\x11\n\rMAIL_LIST_REQ\x10\x01\x12\x16\n\x12MAIL_LIST_RESPONSE\x10\x02\x12\x1c\n\x18GET_MAIL_ATTACHMENTS_REQ\x10\x03\x12!\n\x1dGET_MAIL_ATTACHMENTS_RESPONSE\x10\x04\x12\x17\n\x13GET_ATTACHMENTS_REQ\x10\x05\x12\x1c\n\x18GET_ATTACHMENTS_RESPONSE\x10\x06\x12\x11\n\rREAD_MAIL_REQ\x10\x07\x12\x15\n\x11READ_MAIL_REPONSE\x10\x08')

_PROTOID = descriptor.EnumDescriptor(
  name='ProtoID',
  full_name='protocal.game.MailProto.ProtoID',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='MAIL_LIST_REQ', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MAIL_LIST_RESPONSE', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GET_MAIL_ATTACHMENTS_REQ', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GET_MAIL_ATTACHMENTS_RESPONSE', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GET_ATTACHMENTS_REQ', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GET_ATTACHMENTS_RESPONSE', index=5, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='READ_MAIL_REQ', index=6, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='READ_MAIL_REPONSE', index=7, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=745,
  serialized_end=959,
)


MAIL_LIST_REQ = 1
MAIL_LIST_RESPONSE = 2
GET_MAIL_ATTACHMENTS_REQ = 3
GET_MAIL_ATTACHMENTS_RESPONSE = 4
GET_ATTACHMENTS_REQ = 5
GET_ATTACHMENTS_RESPONSE = 6
READ_MAIL_REQ = 7
READ_MAIL_REPONSE = 8



_MAILINFO = descriptor.Descriptor(
  name='MailInfo',
  full_name='protocal.game.MailProto.MailInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='mailId', full_name='protocal.game.MailProto.MailInfo.mailId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='title', full_name='protocal.game.MailProto.MailInfo.title', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sender', full_name='protocal.game.MailProto.MailInfo.sender', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='icon', full_name='protocal.game.MailProto.MailInfo.icon', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='contents', full_name='protocal.game.MailProto.MailInfo.contents', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='createdTime', full_name='protocal.game.MailProto.MailInfo.createdTime', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status', full_name='protocal.game.MailProto.MailInfo.status', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='attachment', full_name='protocal.game.MailProto.MailInfo.attachment', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=63,
  serialized_end=209,
)


_MAILLISTREQUEST = descriptor.Descriptor(
  name='MailListRequest',
  full_name='protocal.game.MailProto.MailListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='page', full_name='protocal.game.MailProto.MailListRequest.page', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='numPerPage', full_name='protocal.game.MailProto.MailListRequest.numPerPage', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pageNum', full_name='protocal.game.MailProto.MailListRequest.pageNum', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=211,
  serialized_end=279,
)


_MAILLISTRESPONSE = descriptor.Descriptor(
  name='MailListResponse',
  full_name='protocal.game.MailProto.MailListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='maxPage', full_name='protocal.game.MailProto.MailListResponse.maxPage', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mails', full_name='protocal.game.MailProto.MailListResponse.mails', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='isOneKey', full_name='protocal.game.MailProto.MailListResponse.isOneKey', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=281,
  serialized_end=384,
)


_GETMAILATTACHMENTSREQUEST = descriptor.Descriptor(
  name='GetMailAttachmentsRequest',
  full_name='protocal.game.MailProto.GetMailAttachmentsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='mailId', full_name='protocal.game.MailProto.GetMailAttachmentsRequest.mailId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=386,
  serialized_end=429,
)


_GETMAILATTACHMENTSRESPONSE = descriptor.Descriptor(
  name='GetMailAttachmentsResponse',
  full_name='protocal.game.MailProto.GetMailAttachmentsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='status', full_name='protocal.game.MailProto.GetMailAttachmentsResponse.status', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=431,
  serialized_end=475,
)


_GETATTACHMENTSREQUEST = descriptor.Descriptor(
  name='GetAttachmentsRequest',
  full_name='protocal.game.MailProto.GetAttachmentsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=477,
  serialized_end=500,
)


_ATTACHMENTINFO = descriptor.Descriptor(
  name='AttachmentInfo',
  full_name='protocal.game.MailProto.AttachmentInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='title', full_name='protocal.game.MailProto.AttachmentInfo.title', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='date', full_name='protocal.game.MailProto.AttachmentInfo.date', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='attachment', full_name='protocal.game.MailProto.AttachmentInfo.attachment', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=502,
  serialized_end=567,
)


_GETATTACHMENTSRESPONSE = descriptor.Descriptor(
  name='GetAttachmentsResponse',
  full_name='protocal.game.MailProto.GetAttachmentsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='status', full_name='protocal.game.MailProto.GetAttachmentsResponse.status', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='attachments', full_name='protocal.game.MailProto.GetAttachmentsResponse.attachments', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=569,
  serialized_end=671,
)


_READMAILREQUEST = descriptor.Descriptor(
  name='ReadMailRequest',
  full_name='protocal.game.MailProto.ReadMailRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='mailId', full_name='protocal.game.MailProto.ReadMailRequest.mailId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=673,
  serialized_end=706,
)


_READMAILRESPONSE = descriptor.Descriptor(
  name='ReadMailResponse',
  full_name='protocal.game.MailProto.ReadMailResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='status', full_name='protocal.game.MailProto.ReadMailResponse.status', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=708,
  serialized_end=742,
)

_MAILLISTRESPONSE.fields_by_name['mails'].message_type = _MAILINFO
_GETATTACHMENTSRESPONSE.fields_by_name['attachments'].message_type = _ATTACHMENTINFO
DESCRIPTOR.message_types_by_name['MailInfo'] = _MAILINFO
DESCRIPTOR.message_types_by_name['MailListRequest'] = _MAILLISTREQUEST
DESCRIPTOR.message_types_by_name['MailListResponse'] = _MAILLISTRESPONSE
DESCRIPTOR.message_types_by_name['GetMailAttachmentsRequest'] = _GETMAILATTACHMENTSREQUEST
DESCRIPTOR.message_types_by_name['GetMailAttachmentsResponse'] = _GETMAILATTACHMENTSRESPONSE
DESCRIPTOR.message_types_by_name['GetAttachmentsRequest'] = _GETATTACHMENTSREQUEST
DESCRIPTOR.message_types_by_name['AttachmentInfo'] = _ATTACHMENTINFO
DESCRIPTOR.message_types_by_name['GetAttachmentsResponse'] = _GETATTACHMENTSRESPONSE
DESCRIPTOR.message_types_by_name['ReadMailRequest'] = _READMAILREQUEST
DESCRIPTOR.message_types_by_name['ReadMailResponse'] = _READMAILRESPONSE

class MailInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MAILINFO
  
  # @@protoc_insertion_point(class_scope:protocal.game.MailProto.MailInfo)

class MailListRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MAILLISTREQUEST
  
  # @@protoc_insertion_point(class_scope:protocal.game.MailProto.MailListRequest)

class MailListResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MAILLISTRESPONSE
  
  # @@protoc_insertion_point(class_scope:protocal.game.MailProto.MailListResponse)

class GetMailAttachmentsRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETMAILATTACHMENTSREQUEST
  
  # @@protoc_insertion_point(class_scope:protocal.game.MailProto.GetMailAttachmentsRequest)

class GetMailAttachmentsResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETMAILATTACHMENTSRESPONSE
  
  # @@protoc_insertion_point(class_scope:protocal.game.MailProto.GetMailAttachmentsResponse)

class GetAttachmentsRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETATTACHMENTSREQUEST
  
  # @@protoc_insertion_point(class_scope:protocal.game.MailProto.GetAttachmentsRequest)

class AttachmentInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ATTACHMENTINFO
  
  # @@protoc_insertion_point(class_scope:protocal.game.MailProto.AttachmentInfo)

class GetAttachmentsResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETATTACHMENTSRESPONSE
  
  # @@protoc_insertion_point(class_scope:protocal.game.MailProto.GetAttachmentsResponse)

class ReadMailRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _READMAILREQUEST
  
  # @@protoc_insertion_point(class_scope:protocal.game.MailProto.ReadMailRequest)

class ReadMailResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _READMAILRESPONSE
  
  # @@protoc_insertion_point(class_scope:protocal.game.MailProto.ReadMailResponse)

# @@protoc_insertion_point(module_scope)
