# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='gameserver.protocol/GameSvrHeartBeat.proto',
  package='protocal.game.GameSvrHeartBeatProto',
  serialized_pb='\n*gameserver.protocol/GameSvrHeartBeat.proto\x12#protocal.game.GameSvrHeartBeatProto\"\x12\n\x10GameSvrHeartPing\"%\n\x10GameSvrHeartPong\x12\x11\n\tplayerNum\x18\x01 \x02(\x05*3\n\x07ProtoID\x12\x13\n\x0fGAME_HEART_PING\x10\x01\x12\x13\n\x0fGAME_HEART_PONG\x10\x02')

_PROTOID = descriptor.EnumDescriptor(
  name='ProtoID',
  full_name='protocal.game.GameSvrHeartBeatProto.ProtoID',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='GAME_HEART_PING', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAME_HEART_PONG', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=142,
  serialized_end=193,
)


GAME_HEART_PING = 1
GAME_HEART_PONG = 2



_GAMESVRHEARTPING = descriptor.Descriptor(
  name='GameSvrHeartPing',
  full_name='protocal.game.GameSvrHeartBeatProto.GameSvrHeartPing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=83,
  serialized_end=101,
)


_GAMESVRHEARTPONG = descriptor.Descriptor(
  name='GameSvrHeartPong',
  full_name='protocal.game.GameSvrHeartBeatProto.GameSvrHeartPong',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='playerNum', full_name='protocal.game.GameSvrHeartBeatProto.GameSvrHeartPong.playerNum', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=103,
  serialized_end=140,
)

DESCRIPTOR.message_types_by_name['GameSvrHeartPing'] = _GAMESVRHEARTPING
DESCRIPTOR.message_types_by_name['GameSvrHeartPong'] = _GAMESVRHEARTPONG

class GameSvrHeartPing(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GAMESVRHEARTPING
  
  # @@protoc_insertion_point(class_scope:protocal.game.GameSvrHeartBeatProto.GameSvrHeartPing)

class GameSvrHeartPong(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GAMESVRHEARTPONG
  
  # @@protoc_insertion_point(class_scope:protocal.game.GameSvrHeartBeatProto.GameSvrHeartPong)

# @@protoc_insertion_point(module_scope)
