# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='gameserver.protocol/GameSvrSystemIndex.proto',
  package='protocal.game',
  serialized_pb='\n,gameserver.protocol/GameSvrSystemIndex.proto\x12\rprotocal.game*\xc9\x01\n\nSystemType\x12\x10\n\x0cSERVER_ERROR\x10\x01\x12\x15\n\x11GAMESVR_HEARTBEAT\x10\x02\x12\x08\n\x04ROLE\x10\x03\x12\t\n\x05STAGE\x10\x04\x12\r\n\tFORMATION\x10\x05\x12\x0b\n\x07\x45MPLOYE\x10\x06\x12\t\n\x05\x45QUIP\x10\x07\x12\n\n\x06NOTICE\x10\x08\x12\x0c\n\x08INTIMACY\x10\t\x12\x08\n\x04RUNE\x10\n\x12\x08\n\x04SIGN\x10\x0b\x12\x07\n\x03\x42\x41G\x10\x0c\x12\x08\n\x04MAIL\x10\r\x12\x0b\n\x07LOTTERY\x10\x0e\x12\x08\n\x04SHOP\x10\x0f')

_SYSTEMTYPE = descriptor.EnumDescriptor(
  name='SystemType',
  full_name='protocal.game.SystemType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='SERVER_ERROR', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GAMESVR_HEARTBEAT', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ROLE', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STAGE', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FORMATION', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EMPLOYE', index=5, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EQUIP', index=6, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='NOTICE', index=7, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='INTIMACY', index=8, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RUNE', index=9, number=10,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SIGN', index=10, number=11,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BAG', index=11, number=12,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MAIL', index=12, number=13,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LOTTERY', index=13, number=14,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SHOP', index=14, number=15,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=64,
  serialized_end=265,
)


SERVER_ERROR = 1
GAMESVR_HEARTBEAT = 2
ROLE = 3
STAGE = 4
FORMATION = 5
EMPLOYE = 6
EQUIP = 7
NOTICE = 8
INTIMACY = 9
RUNE = 10
SIGN = 11
BAG = 12
MAIL = 13
LOTTERY = 14
SHOP = 15



# @@protoc_insertion_point(module_scope)
